version: '3'

services:
  id_service:
    image: rls42/id-service:1.0.1
    volumes:
      - "./logs:/app/lib/logs"
    environment:
      - "SERVER_PORT=${SERVER_PORT}"
      - "SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}"
      - "SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}"
      - "SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}"
      - "SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}"
      - "SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    logging:
      driver: awslogs
      options: 
        awslogs-group: id_service
        awslogs-region: $CLUSTER_REGION
        awslogs-stream-prefix: id_service