version: '3'

services:
  history_service:
    image: rls42/history-service:0.1.0
    volumes:
      - "./logs:/app/lib/logs"
    environment:
      - "SERVER_PORT=${SERVER_PORT}"
      - "SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}"
      - "SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}"
      - "SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}"
      - "SPRING_DATASOURCE_DRIVER=${SPRING_DATASOURCE_DRIVER}"
      - "SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}"
      - "SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST}"
      - "SPRING_RABBITMQ_PORT=${SPRING_RABBITMQ_PORT}"
      - "SPRING_RABBITMQ_USERNAME=${SPRING_RABBITMQ_USERNAME}"
      - "SPRING_RABBITMQ_PASSWORD=${SPRING_RABBITMQ_PASSWORD}"
    ports:
      - "${SERVER_PORT}"
    logging:
      driver: awslogs
      options:
        awslogs-group: history_service
        awslogs-region: $CLUSTER_REGION
        awslogs-stream-prefix: history_service
